-- =====================================================
-- GreenroomID - Account Management Update
-- Jalankan file ini di Supabase SQL Editor sebelum membuka menu Admin > Manajemen Akun.
-- =====================================================

-- 1. Pastikan tabel admin lama tetap ada sebagai fallback admin awal.
CREATE TABLE IF NOT EXISTS public.admin_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text UNIQUE NOT NULL,
  created_at timestamptz DEFAULT now()
);

INSERT INTO public.admin_users (email)
VALUES ('fajarsiddiqui00@gmail.com')
ON CONFLICT (email) DO NOTHING;

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- 2. Tabel profil akun aplikasi.
CREATE TABLE IF NOT EXISTS public.user_profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text UNIQUE NOT NULL,
  full_name text,
  avatar_url text,
  role text NOT NULL DEFAULT 'client',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz,
  CONSTRAINT user_profiles_role_check CHECK (role IN ('client', 'admin', 'freelancer'))
);

CREATE INDEX IF NOT EXISTS user_profiles_role_idx ON public.user_profiles(role);
CREATE INDEX IF NOT EXISTS user_profiles_email_idx ON public.user_profiles(lower(email));

ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

-- 3. Fungsi cek admin sekarang membaca admin_users dan user_profiles.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    EXISTS (
      SELECT 1
      FROM public.admin_users
      WHERE lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    )
    OR EXISTS (
      SELECT 1
      FROM public.user_profiles
      WHERE id = auth.uid()
        AND role = 'admin'
        AND is_active = true
    );
$$;

GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

-- 4. Proteksi agar client tidak bisa menaikkan role sendiri dari browser.
CREATE OR REPLACE FUNCTION public.protect_user_profile_admin_fields()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF public.is_admin() THEN
    RETURN NEW;
  END IF;

  IF auth.uid() IS NULL OR auth.uid() <> NEW.id THEN
    RAISE EXCEPTION 'Tidak boleh mengubah profil akun lain';
  END IF;

  IF NEW.role IS DISTINCT FROM OLD.role
     OR NEW.is_active IS DISTINCT FROM OLD.is_active THEN
    RAISE EXCEPTION 'Client tidak boleh mengubah role atau status akun';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS protect_user_profile_admin_fields_trigger ON public.user_profiles;
CREATE TRIGGER protect_user_profile_admin_fields_trigger
BEFORE UPDATE ON public.user_profiles
FOR EACH ROW
EXECUTE FUNCTION public.protect_user_profile_admin_fields();

-- 5. Policy profil akun.
DROP POLICY IF EXISTS "User profiles select own or admin" ON public.user_profiles;
DROP POLICY IF EXISTS "User profiles insert own" ON public.user_profiles;
DROP POLICY IF EXISTS "User profiles update own or admin" ON public.user_profiles;

CREATE POLICY "User profiles select own or admin"
ON public.user_profiles
FOR SELECT
TO authenticated
USING (auth.uid() = id OR public.is_admin());

CREATE POLICY "User profiles insert own"
ON public.user_profiles
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = id AND role = 'client');

CREATE POLICY "User profiles update own or admin"
ON public.user_profiles
FOR UPDATE
TO authenticated
USING (auth.uid() = id OR public.is_admin())
WITH CHECK (auth.uid() = id OR public.is_admin());

GRANT SELECT, INSERT, UPDATE ON public.user_profiles TO authenticated;

-- 6. Auto-buat profil untuk user baru dari Supabase Auth.
CREATE OR REPLACE FUNCTION public.handle_new_auth_user_profile()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  INSERT INTO public.user_profiles (
    id,
    email,
    full_name,
    avatar_url,
    role,
    is_active,
    created_at,
    updated_at,
    last_seen_at
  )
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data ->> 'full_name', NEW.raw_user_meta_data ->> 'name'),
    COALESCE(NEW.raw_user_meta_data ->> 'avatar_url', NEW.raw_user_meta_data ->> 'picture'),
    CASE
      WHEN EXISTS (
        SELECT 1 FROM public.admin_users WHERE lower(email) = lower(COALESCE(NEW.email, ''))
      ) THEN 'admin'
      ELSE 'client'
    END,
    true,
    COALESCE(NEW.created_at, now()),
    now(),
    now()
  )
  ON CONFLICT (id) DO NOTHING;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created_create_profile ON auth.users;
CREATE TRIGGER on_auth_user_created_create_profile
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_auth_user_profile();

-- 7. RPC: admin melihat semua akun Supabase Auth beserta role profil.
CREATE OR REPLACE FUNCTION public.admin_list_accounts()
RETURNS TABLE (
  id uuid,
  email text,
  full_name text,
  avatar_url text,
  role text,
  is_active boolean,
  created_at timestamptz,
  last_sign_in_at timestamptz,
  last_seen_at timestamptz,
  profile_created_at timestamptz,
  profile_updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Only admin can list accounts';
  END IF;

  RETURN QUERY
  SELECT
    au.id,
    au.email::text,
    COALESCE(up.full_name, au.raw_user_meta_data ->> 'full_name', au.raw_user_meta_data ->> 'name')::text AS full_name,
    COALESCE(up.avatar_url, au.raw_user_meta_data ->> 'avatar_url', au.raw_user_meta_data ->> 'picture')::text AS avatar_url,
    CASE
      WHEN EXISTS (
        SELECT 1 FROM public.admin_users adm WHERE lower(adm.email) = lower(COALESCE(au.email, ''))
      ) THEN 'admin'
      ELSE COALESCE(up.role, 'client')
    END::text AS role,
    COALESCE(up.is_active, true) AS is_active,
    au.created_at,
    au.last_sign_in_at,
    up.last_seen_at,
    up.created_at AS profile_created_at,
    up.updated_at AS profile_updated_at
  FROM auth.users au
  LEFT JOIN public.user_profiles up ON up.id = au.id
  ORDER BY au.created_at DESC;
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_list_accounts() TO authenticated;

-- 8. RPC: admin mengubah role akun.
CREATE OR REPLACE FUNCTION public.admin_update_user_role(
  target_user_id uuid,
  new_role text
)
RETURNS public.user_profiles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  target_auth_user record;
  updated_profile public.user_profiles;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Only admin can update user role';
  END IF;

  IF new_role NOT IN ('client', 'admin', 'freelancer') THEN
    RAISE EXCEPTION 'Role tidak valid';
  END IF;

  IF target_user_id = auth.uid() AND new_role <> 'admin' THEN
    RAISE EXCEPTION 'Tidak bisa menurunkan role akun admin yang sedang digunakan';
  END IF;

  SELECT
    au.id,
    au.email,
    COALESCE(au.raw_user_meta_data ->> 'full_name', au.raw_user_meta_data ->> 'name') AS full_name,
    COALESCE(au.raw_user_meta_data ->> 'avatar_url', au.raw_user_meta_data ->> 'picture') AS avatar_url,
    au.created_at
  INTO target_auth_user
  FROM auth.users au
  WHERE au.id = target_user_id;

  IF target_auth_user.id IS NULL THEN
    RAISE EXCEPTION 'Akun tidak ditemukan';
  END IF;

  IF new_role <> 'admin' AND EXISTS (
    SELECT 1 FROM public.admin_users adm WHERE lower(adm.email) = lower(COALESCE(target_auth_user.email, ''))
  ) THEN
    RAISE EXCEPTION 'Akun admin utama masih terdaftar di admin_users dan tidak bisa diturunkan dari halaman ini';
  END IF;

  INSERT INTO public.user_profiles (
    id,
    email,
    full_name,
    avatar_url,
    role,
    is_active,
    created_at,
    updated_at
  )
  VALUES (
    target_auth_user.id,
    target_auth_user.email,
    target_auth_user.full_name,
    target_auth_user.avatar_url,
    new_role,
    true,
    COALESCE(target_auth_user.created_at, now()),
    now()
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    full_name = COALESCE(public.user_profiles.full_name, EXCLUDED.full_name),
    avatar_url = COALESCE(public.user_profiles.avatar_url, EXCLUDED.avatar_url),
    role = EXCLUDED.role,
    updated_at = now()
  RETURNING * INTO updated_profile;

  RETURN updated_profile;
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_update_user_role(uuid, text) TO authenticated;
