-- =============================================================
-- GreenroomID - PWA Notification Foundation
-- Jalankan satu kali di Supabase SQL Editor.
-- Tidak menghapus tabel atau fungsi lama.
-- =============================================================

create extension if not exists pgcrypto;

-- Pemeriksaan admin mandiri agar policy notifikasi tidak bergantung pada UI.
create or replace function public.is_notification_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.user_profiles
    where id = auth.uid()
      and role = 'admin'
      and is_active = true
  ) or exists (
    select 1
    from public.admin_users
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

grant execute on function public.is_notification_admin() to authenticated;

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_user_id uuid not null references auth.users(id) on delete cascade,
  activity_log_id text,
  type text not null default 'activity',
  priority text not null default 'info'
    check (priority in ('critical', 'important', 'operational', 'info')),
  title text not null,
  body text,
  target_route text not null default '/admin/audit-logs',
  metadata jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  push_sent_at timestamptz,
  push_failed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_recipient_created_idx
  on public.notifications (recipient_user_id, created_at desc);
create index if not exists notifications_recipient_unread_idx
  on public.notifications (recipient_user_id, read_at, created_at desc);
create unique index if not exists notifications_activity_recipient_unique
  on public.notifications (recipient_user_id, activity_log_id)
  where activity_log_id is not null;

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  fcm_token text not null unique,
  platform text not null default 'web',
  device_name text,
  enabled boolean not null default true,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_enabled_idx
  on public.push_subscriptions (user_id, enabled);

create table if not exists public.notification_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  notification_mode text not null default 'important'
    check (notification_mode in ('important', 'operational', 'all', 'off')),
  request_enabled boolean not null default true,
  payment_enabled boolean not null default true,
  form_enabled boolean not null default true,
  learning_enabled boolean not null default true,
  security_enabled boolean not null default true,
  system_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  notification_id uuid not null references public.notifications(id) on delete cascade,
  push_subscription_id uuid references public.push_subscriptions(id) on delete set null,
  status text not null default 'pending'
    check (status in ('pending', 'sent', 'failed', 'disabled')),
  provider_message_id text,
  failure_reason text,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  failed_at timestamptz
);

create index if not exists notification_deliveries_notification_idx
  on public.notification_deliveries (notification_id, created_at desc);

alter table public.notifications enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.notification_preferences enable row level security;
alter table public.notification_deliveries enable row level security;

drop policy if exists "notifications_select_own_or_admin" on public.notifications;
create policy "notifications_select_own_or_admin"
on public.notifications for select
to authenticated
using (recipient_user_id = auth.uid() or public.is_notification_admin());

drop policy if exists "notifications_update_own_or_admin" on public.notifications;
create policy "notifications_update_own_or_admin"
on public.notifications for update
to authenticated
using (recipient_user_id = auth.uid() or public.is_notification_admin())
with check (recipient_user_id = auth.uid() or public.is_notification_admin());

drop policy if exists "push_subscriptions_select_own_or_admin" on public.push_subscriptions;
create policy "push_subscriptions_select_own_or_admin"
on public.push_subscriptions for select
to authenticated
using (user_id = auth.uid() or public.is_notification_admin());

drop policy if exists "notification_preferences_own_or_admin" on public.notification_preferences;
create policy "notification_preferences_own_or_admin"
on public.notification_preferences for all
to authenticated
using (user_id = auth.uid() or public.is_notification_admin())
with check (user_id = auth.uid() or public.is_notification_admin());

drop policy if exists "notification_deliveries_admin_read" on public.notification_deliveries;
create policy "notification_deliveries_admin_read"
on public.notification_deliveries for select
to authenticated
using (public.is_notification_admin());

grant select, update on public.notifications to authenticated;
grant select on public.push_subscriptions to authenticated;
grant select, insert, update on public.notification_preferences to authenticated;
grant select on public.notification_deliveries to authenticated;

-- Registrasi token dibuat melalui RPC agar satu token tidak tertinggal pada akun lama.
create or replace function public.register_push_subscription(
  p_fcm_token text,
  p_platform text default 'web',
  p_device_name text default null
)
returns public.push_subscriptions
language plpgsql
security definer
set search_path = public
as $$
declare
  saved public.push_subscriptions;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if nullif(trim(p_fcm_token), '') is null then
    raise exception 'FCM token tidak boleh kosong';
  end if;

  insert into public.push_subscriptions (
    user_id, fcm_token, platform, device_name, enabled, last_seen_at, updated_at
  ) values (
    auth.uid(), trim(p_fcm_token), coalesce(nullif(trim(p_platform), ''), 'web'),
    nullif(trim(p_device_name), ''), true, now(), now()
  )
  on conflict (fcm_token) do update set
    user_id = excluded.user_id,
    platform = excluded.platform,
    device_name = excluded.device_name,
    enabled = true,
    last_seen_at = now(),
    updated_at = now()
  returning * into saved;

  insert into public.notification_preferences (user_id)
  values (auth.uid())
  on conflict (user_id) do nothing;

  return saved;
end;
$$;

grant execute on function public.register_push_subscription(text, text, text) to authenticated;

create or replace function public.disable_push_subscription(p_fcm_token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  update public.push_subscriptions
  set enabled = false, updated_at = now()
  where user_id = auth.uid() and fcm_token = p_fcm_token;

  return found;
end;
$$;

grant execute on function public.disable_push_subscription(text) to authenticated;

create or replace function public.disable_all_push_subscriptions()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  update public.push_subscriptions
  set enabled = false, updated_at = now()
  where user_id = auth.uid() and enabled = true;

  get diagnostics affected = row_count;
  return affected;
end;
$$;

grant execute on function public.disable_all_push_subscriptions() to authenticated;

create or replace function public.mark_all_notifications_read()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  update public.notifications
  set read_at = now()
  where recipient_user_id = auth.uid() and read_at is null;

  get diagnostics affected = row_count;
  return affected;
end;
$$;

grant execute on function public.mark_all_notifications_read() to authenticated;

-- Mengubah setiap audit log baru menjadi inbox notification untuk seluruh admin aktif.
create or replace function public.create_admin_notifications_from_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  payload jsonb := to_jsonb(new);
  action_value text := coalesce(nullif(payload ->> 'action', ''), 'activity');
  description_value text := coalesce(nullif(payload ->> 'description', ''), 'Ada aktivitas baru di GreenroomID.');
  request_value text := nullif(payload ->> 'request_id', '');
  log_value text := nullif(payload ->> 'id', '');
  action_search text;
  priority_value text := 'info';
  title_value text;
  route_value text := '/admin/audit-logs';
  admin_record record;
begin
  action_search := lower(action_value || ' ' || description_value);

  if action_search ~ '(security|mencurigakan|gagal|failed|error|hapus permanen|delete permanent)' then
    priority_value := 'critical';
  elsif action_search ~ '(payment|pembayaran|request baru|created request|verifikasi|verified|revisi|deadline)' then
    priority_value := 'important';
  elsif action_search ~ '(form|status|upload|file|learning|pembelajaran|donasi|message|pesan)' then
    priority_value := 'operational';
  end if;

  title_value := initcap(replace(replace(action_value, '_', ' '), '-', ' '));
  if title_value = '' then title_value := 'Aktivitas baru'; end if;

  if request_value is not null then
    route_value := '/admin/requests';
  elsif action_search ~ '(payment|pembayaran)' then
    route_value := '/admin/stats';
  elsif action_search ~ '(form)' then
    route_value := '/admin/forms';
  elsif action_search ~ '(learning|pembelajaran)' then
    route_value := '/admin/ruang-belajar/review';
  elsif action_search ~ '(donasi|donation)' then
    route_value := '/admin/donations';
  end if;

  for admin_record in
    select id from public.user_profiles
    where role = 'admin' and is_active = true
  loop
    insert into public.notifications (
      recipient_user_id,
      activity_log_id,
      type,
      priority,
      title,
      body,
      target_route,
      metadata
    ) values (
      admin_record.id,
      log_value,
      'audit_log',
      priority_value,
      title_value,
      description_value,
      route_value,
      payload
    )
    on conflict do nothing;
  end loop;

  return new;
end;
$$;

drop trigger if exists audit_logs_create_admin_notifications on public.audit_logs;
create trigger audit_logs_create_admin_notifications
after insert on public.audit_logs
for each row execute function public.create_admin_notifications_from_audit_log();

-- Tambahkan tabel ke Supabase Realtime bila belum terdaftar.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'notifications'
  ) then
    alter publication supabase_realtime add table public.notifications;
  end if;
end $$;

-- Notifikasi uji untuk admin yang menjalankan SQL saat sedang login dapat dibuat manual:
-- insert into public.notifications (recipient_user_id, priority, title, body)
-- select id, 'important', 'Notification Center aktif', 'Fondasi notifikasi GreenroomID berhasil dipasang.'
-- from public.user_profiles where role = 'admin' and is_active = true;

-- RPC pengujian end-to-end dari browser admin.
create or replace function public.create_test_push_notification()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  created_id uuid;
begin
  if auth.uid() is null or not public.is_notification_admin() then
    raise exception 'Only admin can create test notification';
  end if;

  insert into public.notifications (
    recipient_user_id,
    type,
    priority,
    title,
    body,
    target_route,
    metadata
  ) values (
    auth.uid(),
    'system_test',
    'important',
    'Tes notifikasi GreenroomID',
    'Jika pesan ini muncul di HP, PWA, Supabase, webhook, dan Firebase sudah terhubung.',
    '/admin',
    jsonb_build_object('source', 'manual_test', 'created_by', auth.uid())
  ) returning id into created_id;

  return created_id;
end;
$$;

grant execute on function public.create_test_push_notification() to authenticated;
