-- =====================================================
-- GreenroomID H+3 Request Files Update
-- Jalankan file ini di Supabase SQL Editor sebelum deploy kode terbaru.
-- Catatan: request_id dibuat text agar aman jika id requests berupa bigint atau uuid.
-- =====================================================

-- =====================================================
-- 1. REQUEST FILES TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS public.request_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id text NOT NULL,
  uploaded_by uuid DEFAULT auth.uid(),
  uploader_email text,
  uploader_role text NOT NULL DEFAULT 'client',
  file_kind text NOT NULL,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_size bigint,
  file_type text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT request_files_uploader_role_check CHECK (
    uploader_role IN ('client', 'admin', 'freelancer', 'system')
  ),
  CONSTRAINT request_files_file_kind_check CHECK (
    file_kind IN (
      'initial_client_file',
      'additional_client_file',
      'preview_file',
      'final_result',
      'revision_result',
      'additional_result',
      'result_file'
    )
  )
);

CREATE INDEX IF NOT EXISTS request_files_request_id_idx
ON public.request_files (request_id);

CREATE INDEX IF NOT EXISTS request_files_file_kind_idx
ON public.request_files (file_kind);

CREATE INDEX IF NOT EXISTS request_files_created_at_idx
ON public.request_files (created_at DESC);

ALTER TABLE public.request_files ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- 2. REQUEST FILES RLS
-- =====================================================

DROP POLICY IF EXISTS "Request files select own request or admin" ON public.request_files;
DROP POLICY IF EXISTS "Request files insert own additional or admin" ON public.request_files;
DROP POLICY IF EXISTS "Request files update admin only" ON public.request_files;
DROP POLICY IF EXISTS "Request files delete admin only" ON public.request_files;

CREATE POLICY "Request files select own request or admin"
ON public.request_files
FOR SELECT
TO authenticated
USING (
  public.is_admin()
  OR EXISTS (
    SELECT 1
    FROM public.requests r
    WHERE r.id::text = request_files.request_id
      AND r.client_id = auth.uid()
      AND (
        request_files.file_kind IN (
          'initial_client_file',
          'additional_client_file',
          'preview_file'
        )
        OR (
          request_files.file_kind IN (
            'final_result',
            'revision_result',
            'additional_result',
            'result_file'
          )
          AND (
            r.payment_status = 'VERIFIED'
            OR r.invoice_status = 'PAID'
          )
        )
      )
  )
);

CREATE POLICY "Request files insert own additional or admin"
ON public.request_files
FOR INSERT
TO authenticated
WITH CHECK (
  public.is_admin()
  OR (
    uploaded_by = auth.uid()
    AND uploader_role = 'client'
    AND file_kind IN ('initial_client_file', 'additional_client_file')
    AND EXISTS (
      SELECT 1
      FROM public.requests r
      WHERE r.id::text = request_files.request_id
        AND r.client_id = auth.uid()
    )
  )
);

CREATE POLICY "Request files update admin only"
ON public.request_files
FOR UPDATE
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

CREATE POLICY "Request files delete admin only"
ON public.request_files
FOR DELETE
TO authenticated
USING (public.is_admin());

-- =====================================================
-- 3. OPTIONAL BACKFILL FROM LEGACY REQUEST COLUMNS
-- Jalankan aman berkali-kali. Ini membantu data lama tetap muncul di tabel baru.
-- =====================================================

INSERT INTO public.request_files (
  request_id,
  uploader_email,
  uploader_role,
  file_kind,
  file_name,
  file_url,
  file_size,
  file_type,
  created_at
)
SELECT
  r.id::text,
  r.client_email,
  'client',
  'initial_client_file',
  'File Client Lama',
  r.file_url,
  NULL,
  NULL,
  COALESCE(r.created_at, now())
FROM public.requests r
WHERE r.file_url IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.request_files rf
    WHERE rf.request_id = r.id::text
      AND rf.file_url = r.file_url
  );

INSERT INTO public.request_files (
  request_id,
  uploader_role,
  file_kind,
  file_name,
  file_url,
  file_size,
  file_type,
  created_at
)
SELECT
  r.id::text,
  'admin',
  'result_file',
  'File Hasil Lama',
  r.hasil_url,
  NULL,
  NULL,
  now()
FROM public.requests r
WHERE r.hasil_url IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.request_files rf
    WHERE rf.request_id = r.id::text
      AND rf.file_url = r.hasil_url
  );

-- =====================================================
-- 4. AUDIT LOG ACTIONS
-- Tidak perlu alter tabel jika audit_logs sudah punya action text dan metadata jsonb.
-- Action baru yang akan masuk dari frontend:
-- PREVIEW_FILE_UPLOADED
-- RESULT_UPLOADED
-- REVISION_RESULT_UPLOADED
-- CLIENT_ADDITIONAL_FILE_UPLOADED
-- STATUS_CHANGED
-- PAYMENT_STATUS_CHANGED
-- ADMIN_MESSAGE_SENT
-- CLIENT_MESSAGE_SENT
-- =====================================================
