-- =====================================================
-- GreenroomID Supabase RLS Backup
-- Last updated: after requests, diskusi, page_views, and storage hardening
-- =====================================================


-- =====================================================
-- 1. ADMIN USERS
-- =====================================================

CREATE TABLE IF NOT EXISTS public.admin_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text UNIQUE NOT NULL,
  created_at timestamptz DEFAULT now()
);

INSERT INTO public.admin_users (email)
VALUES ('fajarsiddiqui00@gmail.com')
ON CONFLICT (email) DO NOTHING;

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;


-- =====================================================
-- 2. ADMIN CHECK FUNCTION
-- =====================================================

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.admin_users
    WHERE lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;


-- =====================================================
-- 3. PAGE VIEWS TABLE AND PUBLIC STATS
-- =====================================================

CREATE TABLE IF NOT EXISTS public.page_views (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id text,
  path text DEFAULT '/',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.page_views ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert page views" ON public.page_views;

CREATE POLICY "Allow public insert page views"
ON public.page_views
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.track_page_view(
  p_visitor_id text,
  p_path text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.page_views (visitor_id, path)
  VALUES (
    left(coalesce(p_visitor_id, 'anonymous'), 100),
    left(coalesce(p_path, '/'), 200)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.get_public_stats()
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'total_views', (
      SELECT count(*)
      FROM public.page_views
    ),
    'total_requests', (
      SELECT count(*)
      FROM public.requests
    ),
    'completed_requests', (
      SELECT count(*)
      FROM public.requests
      WHERE status = 'DONE'
    ),
    'service_categories', 4
  );
$$;

GRANT EXECUTE ON FUNCTION public.track_page_view(text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_stats() TO anon, authenticated;


-- =====================================================
-- 4. REQUESTS RLS
-- =====================================================

ALTER TABLE public.requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Requests select own or admin" ON public.requests;
DROP POLICY IF EXISTS "Requests insert own" ON public.requests;
DROP POLICY IF EXISTS "Requests update own or admin" ON public.requests;

CREATE POLICY "Requests select own or admin"
ON public.requests
FOR SELECT
TO authenticated
USING (
  client_id = auth.uid()
  OR public.is_admin()
);

CREATE POLICY "Requests insert own"
ON public.requests
FOR INSERT
TO authenticated
WITH CHECK (
  client_id = auth.uid()
  AND lower(client_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

CREATE POLICY "Requests update own or admin"
ON public.requests
FOR UPDATE
TO authenticated
USING (
  client_id = auth.uid()
  OR public.is_admin()
)
WITH CHECK (
  client_id = auth.uid()
  OR public.is_admin()
);


-- =====================================================
-- 5. PROTECT REQUEST ADMIN FIELDS
-- =====================================================

CREATE OR REPLACE FUNCTION public.protect_request_admin_fields()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF public.is_admin() THEN
    RETURN NEW;
  END IF;

  IF OLD.client_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'Tidak boleh mengubah request milik user lain';
  END IF;

  IF NEW.id IS DISTINCT FROM OLD.id
    OR NEW.created_at IS DISTINCT FROM OLD.created_at
    OR NEW.client_id IS DISTINCT FROM OLD.client_id
    OR NEW.client_email IS DISTINCT FROM OLD.client_email
    OR NEW.judul IS DISTINCT FROM OLD.judul
    OR NEW.deskripsi IS DISTINCT FROM OLD.deskripsi
    OR NEW.kategori IS DISTINCT FROM OLD.kategori
    OR NEW.file_url IS DISTINCT FROM OLD.file_url
    OR NEW.file_urls IS DISTINCT FROM OLD.file_urls
    OR NEW.harga IS DISTINCT FROM OLD.harga
    OR NEW.deadline_at IS DISTINCT FROM OLD.deadline_at
    OR NEW.invoice_status IS DISTINCT FROM OLD.invoice_status
    OR NEW.hasil_url IS DISTINCT FROM OLD.hasil_url
    OR NEW.admin_note IS DISTINCT FROM OLD.admin_note
  THEN
    RAISE EXCEPTION 'Client tidak boleh mengubah data admin request';
  END IF;

  IF NEW.status IS DISTINCT FROM OLD.status
    AND NEW.status <> 'PAYMENT UPLOADED'
  THEN
    RAISE EXCEPTION 'Client hanya boleh mengubah status menjadi PAYMENT UPLOADED';
  END IF;

  IF NEW.payment_status IS DISTINCT FROM OLD.payment_status
    AND NEW.payment_status <> 'UPLOADED'
  THEN
    RAISE EXCEPTION 'Client tidak boleh mengubah status pembayaran selain UPLOADED';
  END IF;

  IF NEW.payment_proof_url IS DISTINCT FROM OLD.payment_proof_url
    AND NEW.payment_proof_url IS NULL
  THEN
    RAISE EXCEPTION 'Bukti pembayaran tidak boleh dikosongkan';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS protect_request_admin_fields_trigger ON public.requests;

CREATE TRIGGER protect_request_admin_fields_trigger
BEFORE UPDATE ON public.requests
FOR EACH ROW
EXECUTE FUNCTION public.protect_request_admin_fields();


-- =====================================================
-- 6. DISKUSI RLS
-- =====================================================

ALTER TABLE public.diskusi ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Diskusi select own request or admin" ON public.diskusi;
DROP POLICY IF EXISTS "Diskusi insert own request or admin" ON public.diskusi;

CREATE POLICY "Diskusi select own request or admin"
ON public.diskusi
FOR SELECT
TO authenticated
USING (
  public.is_admin()
  OR EXISTS (
    SELECT 1
    FROM public.requests r
    WHERE r.id = diskusi.request_id
    AND r.client_id = auth.uid()
  )
);

CREATE POLICY "Diskusi insert own request or admin"
ON public.diskusi
FOR INSERT
TO authenticated
WITH CHECK (
  lower(pengirim_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  AND (
    public.is_admin()
    OR EXISTS (
      SELECT 1
      FROM public.requests r
      WHERE r.id = diskusi.request_id
      AND r.client_id = auth.uid()
    )
  )
);


-- =====================================================
-- 7. STORAGE POLICIES
-- Bucket: request-files
-- =====================================================

DROP POLICY IF EXISTS "Allow public uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated uploads" ON storage.objects;

CREATE POLICY "Allow authenticated uploads"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'request-files'
);

DROP POLICY IF EXISTS "Allow public read" ON storage.objects;

CREATE POLICY "Allow public read"
ON storage.objects
FOR SELECT
TO anon, authenticated
USING (
  bucket_id = 'request-files'
);-- =====================================================
-- GreenroomID H+3 Request Files Update
-- Jalankan file ini di Supabase SQL Editor sebelum deploy kode terbaru.
-- Catatan: request_id dibuat text agar aman jika id requests berupa bigint atau uuid.
-- =====================================================

-- =====================================================
-- 1. REQUEST FILES TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS public.request_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id text NOT NULL,
  uploaded_by uuid DEFAULT auth.uid(),
  uploader_email text,
  uploader_role text NOT NULL DEFAULT 'client',
  file_kind text NOT NULL,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_size bigint,
  file_type text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT request_files_uploader_role_check CHECK (
    uploader_role IN ('client', 'admin', 'freelancer', 'system')
  ),
  CONSTRAINT request_files_file_kind_check CHECK (
    file_kind IN (
      'initial_client_file',
      'additional_client_file',
      'preview_file',
      'final_result',
      'revision_result',
      'additional_result',
      'result_file'
    )
  )
);

CREATE INDEX IF NOT EXISTS request_files_request_id_idx
ON public.request_files (request_id);

CREATE INDEX IF NOT EXISTS request_files_file_kind_idx
ON public.request_files (file_kind);

CREATE INDEX IF NOT EXISTS request_files_created_at_idx
ON public.request_files (created_at DESC);

ALTER TABLE public.request_files ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- 2. REQUEST FILES RLS
-- =====================================================

DROP POLICY IF EXISTS "Request files select own request or admin" ON public.request_files;
DROP POLICY IF EXISTS "Request files insert own additional or admin" ON public.request_files;
DROP POLICY IF EXISTS "Request files update admin only" ON public.request_files;
DROP POLICY IF EXISTS "Request files delete admin only" ON public.request_files;

CREATE POLICY "Request files select own request or admin"
ON public.request_files
FOR SELECT
TO authenticated
USING (
  public.is_admin()
  OR EXISTS (
    SELECT 1
    FROM public.requests r
    WHERE r.id::text = request_files.request_id
      AND r.client_id = auth.uid()
      AND (
        request_files.file_kind IN (
          'initial_client_file',
          'additional_client_file',
          'preview_file'
        )
        OR (
          request_files.file_kind IN (
            'final_result',
            'revision_result',
            'additional_result',
            'result_file'
          )
          AND (
            r.payment_status = 'VERIFIED'
            OR r.invoice_status = 'PAID'
          )
        )
      )
  )
);

CREATE POLICY "Request files insert own additional or admin"
ON public.request_files
FOR INSERT
TO authenticated
WITH CHECK (
  public.is_admin()
  OR (
    uploaded_by = auth.uid()
    AND uploader_role = 'client'
    AND file_kind IN ('initial_client_file', 'additional_client_file')
    AND EXISTS (
      SELECT 1
      FROM public.requests r
      WHERE r.id::text = request_files.request_id
        AND r.client_id = auth.uid()
    )
  )
);

CREATE POLICY "Request files update admin only"
ON public.request_files
FOR UPDATE
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

CREATE POLICY "Request files delete admin only"
ON public.request_files
FOR DELETE
TO authenticated
USING (public.is_admin());

-- =====================================================
-- 3. OPTIONAL BACKFILL FROM LEGACY REQUEST COLUMNS
-- Jalankan aman berkali-kali. Ini membantu data lama tetap muncul di tabel baru.
-- =====================================================

INSERT INTO public.request_files (
  request_id,
  uploader_email,
  uploader_role,
  file_kind,
  file_name,
  file_url,
  file_size,
  file_type,
  created_at
)
SELECT
  r.id::text,
  r.client_email,
  'client',
  'initial_client_file',
  'File Client Lama',
  r.file_url,
  NULL,
  NULL,
  COALESCE(r.created_at, now())
FROM public.requests r
WHERE r.file_url IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.request_files rf
    WHERE rf.request_id = r.id::text
      AND rf.file_url = r.file_url
  );

INSERT INTO public.request_files (
  request_id,
  uploader_role,
  file_kind,
  file_name,
  file_url,
  file_size,
  file_type,
  created_at
)
SELECT
  r.id::text,
  'admin',
  'result_file',
  'File Hasil Lama',
  r.hasil_url,
  NULL,
  NULL,
  now()
FROM public.requests r
WHERE r.hasil_url IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.request_files rf
    WHERE rf.request_id = r.id::text
      AND rf.file_url = r.hasil_url
  );

-- =====================================================
-- 4. AUDIT LOG ACTIONS
-- Tidak perlu alter tabel jika audit_logs sudah punya action text dan metadata jsonb.
-- Action baru yang akan masuk dari frontend:
-- PREVIEW_FILE_UPLOADED
-- RESULT_UPLOADED
-- REVISION_RESULT_UPLOADED
-- CLIENT_ADDITIONAL_FILE_UPLOADED
-- STATUS_CHANGED
-- PAYMENT_STATUS_CHANGED
-- ADMIN_MESSAGE_SENT
-- CLIENT_MESSAGE_SENT
-- =====================================================
