-- =====================================================
-- GreenroomID Supabase RLS Backup
-- Last updated: after requests, diskusi, page_views, and storage hardening
-- =====================================================


-- =====================================================
-- 1. ADMIN USERS
-- =====================================================

CREATE TABLE IF NOT EXISTS public.admin_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text UNIQUE NOT NULL,
  created_at timestamptz DEFAULT now()
);

INSERT INTO public.admin_users (email)
VALUES ('fajarsiddiqui00@gmail.com')
ON CONFLICT (email) DO NOTHING;

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;


-- =====================================================
-- 2. ADMIN CHECK FUNCTION
-- =====================================================

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.admin_users
    WHERE lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;


-- =====================================================
-- 3. PAGE VIEWS TABLE AND PUBLIC STATS
-- =====================================================

CREATE TABLE IF NOT EXISTS public.page_views (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id text,
  path text DEFAULT '/',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.page_views ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert page views" ON public.page_views;

CREATE POLICY "Allow public insert page views"
ON public.page_views
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.track_page_view(
  p_visitor_id text,
  p_path text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.page_views (visitor_id, path)
  VALUES (
    left(coalesce(p_visitor_id, 'anonymous'), 100),
    left(coalesce(p_path, '/'), 200)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.get_public_stats()
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'total_views', (
      SELECT count(*)
      FROM public.page_views
    ),
    'total_requests', (
      SELECT count(*)
      FROM public.requests
    ),
    'completed_requests', (
      SELECT count(*)
      FROM public.requests
      WHERE status = 'DONE'
    ),
    'service_categories', 4
  );
$$;

GRANT EXECUTE ON FUNCTION public.track_page_view(text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_stats() TO anon, authenticated;


-- =====================================================
-- 4. REQUESTS RLS
-- =====================================================

ALTER TABLE public.requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Requests select own or admin" ON public.requests;
DROP POLICY IF EXISTS "Requests insert own" ON public.requests;
DROP POLICY IF EXISTS "Requests update own or admin" ON public.requests;

CREATE POLICY "Requests select own or admin"
ON public.requests
FOR SELECT
TO authenticated
USING (
  client_id = auth.uid()
  OR public.is_admin()
);

CREATE POLICY "Requests insert own"
ON public.requests
FOR INSERT
TO authenticated
WITH CHECK (
  client_id = auth.uid()
  AND lower(client_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

CREATE POLICY "Requests update own or admin"
ON public.requests
FOR UPDATE
TO authenticated
USING (
  client_id = auth.uid()
  OR public.is_admin()
)
WITH CHECK (
  client_id = auth.uid()
  OR public.is_admin()
);


-- =====================================================
-- 5. PROTECT REQUEST ADMIN FIELDS
-- =====================================================

CREATE OR REPLACE FUNCTION public.protect_request_admin_fields()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF public.is_admin() THEN
    RETURN NEW;
  END IF;

  IF OLD.client_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'Tidak boleh mengubah request milik user lain';
  END IF;

  IF NEW.id IS DISTINCT FROM OLD.id
    OR NEW.created_at IS DISTINCT FROM OLD.created_at
    OR NEW.client_id IS DISTINCT FROM OLD.client_id
    OR NEW.client_email IS DISTINCT FROM OLD.client_email
    OR NEW.judul IS DISTINCT FROM OLD.judul
    OR NEW.deskripsi IS DISTINCT FROM OLD.deskripsi
    OR NEW.kategori IS DISTINCT FROM OLD.kategori
    OR NEW.file_url IS DISTINCT FROM OLD.file_url
    OR NEW.file_urls IS DISTINCT FROM OLD.file_urls
    OR NEW.harga IS DISTINCT FROM OLD.harga
    OR NEW.deadline_at IS DISTINCT FROM OLD.deadline_at
    OR NEW.invoice_status IS DISTINCT FROM OLD.invoice_status
    OR NEW.hasil_url IS DISTINCT FROM OLD.hasil_url
    OR NEW.admin_note IS DISTINCT FROM OLD.admin_note
  THEN
    RAISE EXCEPTION 'Client tidak boleh mengubah data admin request';
  END IF;

  IF NEW.status IS DISTINCT FROM OLD.status
    AND NEW.status <> 'PAYMENT UPLOADED'
  THEN
    RAISE EXCEPTION 'Client hanya boleh mengubah status menjadi PAYMENT UPLOADED';
  END IF;

  IF NEW.payment_status IS DISTINCT FROM OLD.payment_status
    AND NEW.payment_status <> 'UPLOADED'
  THEN
    RAISE EXCEPTION 'Client tidak boleh mengubah status pembayaran selain UPLOADED';
  END IF;

  IF NEW.payment_proof_url IS DISTINCT FROM OLD.payment_proof_url
    AND NEW.payment_proof_url IS NULL
  THEN
    RAISE EXCEPTION 'Bukti pembayaran tidak boleh dikosongkan';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS protect_request_admin_fields_trigger ON public.requests;

CREATE TRIGGER protect_request_admin_fields_trigger
BEFORE UPDATE ON public.requests
FOR EACH ROW
EXECUTE FUNCTION public.protect_request_admin_fields();


-- =====================================================
-- 6. DISKUSI RLS
-- =====================================================

ALTER TABLE public.diskusi ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Diskusi select own request or admin" ON public.diskusi;
DROP POLICY IF EXISTS "Diskusi insert own request or admin" ON public.diskusi;

CREATE POLICY "Diskusi select own request or admin"
ON public.diskusi
FOR SELECT
TO authenticated
USING (
  public.is_admin()
  OR EXISTS (
    SELECT 1
    FROM public.requests r
    WHERE r.id = diskusi.request_id
    AND r.client_id = auth.uid()
  )
);

CREATE POLICY "Diskusi insert own request or admin"
ON public.diskusi
FOR INSERT
TO authenticated
WITH CHECK (
  lower(pengirim_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  AND (
    public.is_admin()
    OR EXISTS (
      SELECT 1
      FROM public.requests r
      WHERE r.id = diskusi.request_id
      AND r.client_id = auth.uid()
    )
  )
);


-- =====================================================
-- 7. STORAGE POLICIES
-- Bucket: request-files
-- =====================================================

DROP POLICY IF EXISTS "Allow public uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated uploads" ON storage.objects;

CREATE POLICY "Allow authenticated uploads"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'request-files'
);

DROP POLICY IF EXISTS "Allow public read" ON storage.objects;

CREATE POLICY "Allow public read"
ON storage.objects
FOR SELECT
TO anon, authenticated
USING (
  bucket_id = 'request-files'
);